package di

import (
	_ "embed"
	"text/template"
)

//go:embed templates/README.md
var readmeTemplate string

var headingTemplate = template.Must(template.New("heading").Parse(`// Code generated by DIGEN; DO NOT EDIT.
// This file was generated by Dependency Injection Container Generator {{.Version}}.
// See docs at https://github.com/strider2038/digen

`))

const definitionsContainerFileSkeleton = `package definitions

// Container is a root dependency injection container. It is required to describe
// your services.
type Container struct {
	// put the list of your services here
	// for example
	//  log *log.Logger

	// also, you can describe your services in a separate container
	// repositories RepositoryContainer
}

// this is a separate container
// type RepositoryContainer {
// 	entityRepository domain.EntityRepository
// }
`
