package di

import (
	_ "embed"
	"text/template"
)

//go:embed templates/README.md
var readmeTemplate string

var headingTemplate = template.Must(template.New("heading").Parse(`// Code generated by DIGEN; DO NOT EDIT.
// This file was generated by Dependency Injection Container Generator {{.Version}}.
// See docs at https://github.com/strider2038/digen

`))

const definitionsContainerFileSkeleton = `package definitions

// Container is a root dependency injection container. It is required to describe
// your services.
type Container struct {
	// put the list of your services here
	// for example
	//  log *log.Logger

	// also, you can describe your services in a separate container
	// repositories RepositoryContainer
}

// this is a separate container
// type RepositoryContainer {
// 	entityRepository domain.EntityRepository
// }
`

const bitsetSkeleton = `package internal

type bitset []uint64

func (b *bitset) Set(n int) {
	i, j := b.split(n)
	for i >= len(*b) {
		*b = append(*b, 0)
	}

	(*b)[i] = (*b)[i] | (1 << j)
}

func (b bitset) IsSet(n int) bool {
	i, j := b.split(n)
	if i >= len(b) {
		return false
	}

	return b[i]&(1<<j) != 0
}

func (b *bitset) split(n int) (int, int) {
	return n >> 6, n & 0x3F
}
`
