// Code generated by DIGEN; DO NOT EDIT.
// This file was generated by Dependency Injection Container Generator rev-4a52da2-dirty.
// See docs at https://github.com/strider2038/digen
package internal

import (
	config "basic/app/config"
	domain "basic/app/domain"
	httphandler "basic/app/httphandler"
	usecase "basic/app/usecase"
	factories "basic/di/internal/factories"
	lookup "basic/di/lookup"
	"context"
	"database/sql"
	"errors"
	"log"
	"net/http"
	"time"
)

const (
	id_Config = iota
	id_Logger
	id_DB
	id_Server
	id_Params_ServerPort
	id_Params_ServerHost
	id_Params_RequestTimeout
	id_API_FindEntityHandler
	id_UseCases_FindEntity
	id_Repositories_EntityRepository
)

type Container struct {
	errs []error
	init bitset

	config config.Params
	logger *log.Logger
	db     *sql.DB
	server *http.Server

	params       *ParamsContainer
	api          *APIContainer
	useCases     *UseCaseContainer
	repositories *RepositoryContainer
}

func NewContainer() *Container {
	c := &Container{}
	c.init = make(bitset, 1)
	c.params = &ParamsContainer{Container: c}
	c.api = &APIContainer{Container: c}
	c.useCases = &UseCaseContainer{Container: c}
	c.repositories = &RepositoryContainer{Container: c}

	return c
}

// Error returns the first initialization error, which can be set via SetError in a service definition.
func (c *Container) Error() error {
	return errors.Join(c.errs...)
}

// SetError sets the first error into container. The error is used in the public container to return an initialization error.
// Deprecated. Return error in factory instead.
func (c *Container) SetError(err error) {
	c.addError(err)
}

func (c *Container) addError(err error) {
	if err != nil {
		c.errs = append(c.errs, err)
	}
}

type ParamsContainer struct {
	*Container

	serverPort     int
	serverHost     string
	requestTimeout time.Duration
}

type APIContainer struct {
	*Container

	findEntityHandler *httphandler.FindEntity
}

type UseCaseContainer struct {
	*Container

	findEntity *usecase.FindEntity
}

type RepositoryContainer struct {
	*Container

	entityRepository domain.EntityRepository
}

func (c *Container) Config(ctx context.Context) config.Params {
	return c.config
}

func (c *Container) Logger(ctx context.Context) *log.Logger {
	if !c.init.IsSet(id_Logger) && c.errs == nil {
		c.logger = factories.CreateLogger(ctx, c)
		c.init.Set(id_Logger)
	}
	return c.logger
}

func (c *Container) DB(ctx context.Context) *sql.DB {
	if !c.init.IsSet(id_DB) && c.errs == nil {
		c.db = factories.CreateDB(ctx, c)
		c.init.Set(id_DB)
	}
	return c.db
}

func (c *Container) Server(ctx context.Context) *http.Server {
	if !c.init.IsSet(id_Server) && c.errs == nil {
		c.server = factories.CreateServer(ctx, c)
		c.init.Set(id_Server)
	}
	return c.server
}

func (c *Container) Params() lookup.ParamsContainer {
	return c.params
}

func (c *ParamsContainer) ServerPort(ctx context.Context) int {
	if !c.init.IsSet(id_Params_ServerPort) && c.errs == nil {
		c.serverPort = factories.CreateParamsServerPort(ctx, c)
		c.init.Set(id_Params_ServerPort)
	}
	return c.serverPort
}

func (c *ParamsContainer) ServerHost(ctx context.Context) string {
	if !c.init.IsSet(id_Params_ServerHost) && c.errs == nil {
		c.serverHost = factories.CreateParamsServerHost(ctx, c)
		c.init.Set(id_Params_ServerHost)
	}
	return c.serverHost
}

func (c *ParamsContainer) RequestTimeout(ctx context.Context) time.Duration {
	if !c.init.IsSet(id_Params_RequestTimeout) && c.errs == nil {
		c.requestTimeout = factories.CreateParamsRequestTimeout(ctx, c)
		c.init.Set(id_Params_RequestTimeout)
	}
	return c.requestTimeout
}

func (c *Container) API() lookup.APIContainer {
	return c.api
}

func (c *APIContainer) FindEntityHandler(ctx context.Context) *httphandler.FindEntity {
	if !c.init.IsSet(id_API_FindEntityHandler) && c.errs == nil {
		c.findEntityHandler = factories.CreateAPIFindEntityHandler(ctx, c)
		c.init.Set(id_API_FindEntityHandler)
	}
	return c.findEntityHandler
}

func (c *Container) UseCases() lookup.UseCaseContainer {
	return c.useCases
}

func (c *UseCaseContainer) FindEntity(ctx context.Context) *usecase.FindEntity {
	if !c.init.IsSet(id_UseCases_FindEntity) && c.errs == nil {
		c.findEntity = factories.CreateUseCasesFindEntity(ctx, c)
		c.init.Set(id_UseCases_FindEntity)
	}
	return c.findEntity
}

func (c *Container) Repositories() lookup.RepositoryContainer {
	return c.repositories
}

func (c *RepositoryContainer) EntityRepository(ctx context.Context) domain.EntityRepository {
	if !c.init.IsSet(id_Repositories_EntityRepository) && c.errs == nil {
		c.entityRepository = factories.CreateRepositoriesEntityRepository(ctx, c)
		c.init.Set(id_Repositories_EntityRepository)
	}
	return c.entityRepository
}

func (c *Container) SetConfig(s config.Params) {
	c.config = s
	c.init.Set(id_Config)
}

func (c *RepositoryContainer) SetEntityRepository(s domain.EntityRepository) {
	c.entityRepository = s
	c.init.Set(id_Repositories_EntityRepository)
}

func (c *Container) Close() {
	if c.init.IsSet(id_DB) {
		c.db.Close()
	}
	if c.init.IsSet(id_Server) {
		c.server.Close()
	}
}
